// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjGhto7TkBfJDAeALV0EZeNCIVzKq94rQ',
    appId: '1:371659154751:web:31fe1741b723b1ea18df8a',
    messagingSenderId: '371659154751',
    projectId: 'pufferfish-math',
    authDomain: 'pufferfish-math.firebaseapp.com',
    storageBucket: 'pufferfish-math.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXMzxMOL1gJMfnTxvwfn-jvZ2OnvWwb8',
    appId: '1:371659154751:android:81c8bf9cd739086318df8a',
    messagingSenderId: '371659154751',
    projectId: 'pufferfish-math',
    storageBucket: 'pufferfish-math.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKs7xZq_THqFYt8kkLxtXBOIvZXBxCvA',
    appId: '1:371659154751:ios:6859e6e8d9bd2c8d18df8a',
    messagingSenderId: '371659154751',
    projectId: 'pufferfish-math',
    storageBucket: 'pufferfish-math.firebasestorage.app',
    iosBundleId: 'com.puff.proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrKs7xZq_THqFYt8kkLxtXBOIvZXBxCvA',
    appId: '1:371659154751:ios:6859e6e8d9bd2c8d18df8a',
    messagingSenderId: '371659154751',
    projectId: 'pufferfish-math',
    storageBucket: 'pufferfish-math.firebasestorage.app',
    iosBundleId: 'com.puff.proyecto',
  );
}
